context:
  name: choreographer
  version: "1.0.10"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
    sha256: 7adf84a0d6a6054386d5cce013fdcadb2426479e49c9b0cb06af7d3712ed263c

build:
  number: 0
  noarch: python
  script: |
    rm -rf tests && rm -rf results
    ${{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools-git-versioning
  run:
    - python >=${{ python_min }}
    - logistro >=1.0.11
    - simplejson >=3.19.3

tests:
  - python:
      imports:
        - choreographer
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/plotly/choreographer
  license: MIT
  license_file: LICENSE.md
  summary: |
    choreographer allows remote control of browsers from Python.
    It was created to support image generation from browser-based charting tools, but can be used for other purposes as well.
  repository: https://github.com/plotly/choreographer

extra:
  recipe-maintainers:
    - ytausch
