context:
  name: choreographer
  version: "1.4.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://files.pythonhosted.org/packages/cc/21/6b1a021b5fd16696bef7e12093ada05bce6fc3a354d529f67381fc3e83d1/choreographer-${{ version }}.tar.gz
    sha256: 97ed6d2b44b71271b6cd9fc87816d23bef4fd5eca9855dc24dfa0033ebf08c77

build:
  number: 0
  noarch: python
  script: |
    rm -rf tests && rm -rf results
    ${{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools-git-versioning
  run:
    - python >=${{ python_min }}
    - logistro >=2.0.1
    - platformdirs >=4.3.6
    - simplejson >=3.19.3

tests:
  - python:
      imports:
        - choreographer
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/plotly/choreographer
  license: MIT
  license_file: LICENSE.md
  summary: |
    choreographer allows remote control of browsers from Python.
    It was created to support image generation from browser-based charting tools, but can be used for other purposes as well.
  repository: https://github.com/plotly/choreographer

extra:
  recipe-maintainers:
    - ytausch
